export const ACTION_TYPE = {
	SET_CATEGORY_ID: 'SET_CATEGORY_ID',
	SET_PRODUCTS: 'SET_PRODUCTS',
	SET_PRODUCTS_LOADING: 'SET_PRODUCTS_LOADING',
	SET_SORT_ORDER: 'SET_SORT_ORDER',
	SET_CATEGORIES: 'SET_CATEGORIES',
	SET_CATEGORIES_LOADING: 'SET_CATEGORIES_LOADING',
	SET_USERS: 'SET_USERS',
	SET_CART: 'SET_CART',
	SET_DRAWER_VISIBILITY: 'SET_DRAWER_VISIBILITY',
	SET_LAST_PAGE: 'SET_LAST_PAGE',
	SET_SCROLLER: 'SET_SCROLLER',
};
